### ISSUE TITLE
Invalid version constraint in recent pubspec.yaml

### ISSUE THREAD

**Issue by dirvens** [dart-lang/source_maps#1]
Our build server is throwing an error based on the recent changes to the source_maps/pubspec.yaml file. The dart sdk version we have been using sucessfully for over a year to build a GUI throws the following error:

[exec] Error in pubspec for package "source_maps" loaded from https://pub.dartlang.org/api/packages/source_maps/versions/0.10.0%2B2:
     [exec] Invalid version constraint for "dependencies.path": Could not parse version "^1.2.0". Unknown text at "^1.2.0".
     [exec] Result: 1

Where there changes to the pubspec specification that now allow for carets?

Thanks, 

-Dirv

**Comment by nex3** [comment]
This has been a valid version constraint since Dart 1.8.0. Since the pubspec includes an SDK constraint that indicates it won't work with pre-1.8.0 SDKs, it's free to use this syntax. Only very old pub versions  will ignore the SDK constraint and try to parse this anyway; if yours is that old, I suggest upgrading.
