### ISSUE TITLE
How to get source maps from dart2js compiled files and deferred loading?

### ISSUE THREAD

**Issue by gregory112** [dart-lang/source_maps#59]
Hi,
I am trying to use source_map_stack_trace package and in the example it requires me to get the source map in code.

```dart
var mapping = // Get a source map mapping the JS to the Dart source.

// Convert jsTrace to refer to the Dart source instead.
var dartTrace = mapStackTrace(jsTrace, sourceMap);
```

I do not understand how to get the mapping. During compiling, I know that dart2js outputs a source map with .map extension. Should I fetch the file in code with HTTP or with other methods? If so, dart2js with deferred loading generates maps for all part.js files. How can I retrieve those source maps in code?

**Comment by fhuonder** [comment]
Do you have a solution? I am facing the same problem.

**Comment by sigmundch** [comment]
### Locating files

In terms of how to fetch the .map file, depends on where the mapping is happening, the solution may be different.

* **Client side** (usually not recommended): it is possible to deobfuscate the stack direclty in the client. This can be done by using an XHR request to load the .map file and deserialize it. It would require that your web server host the .map file next to the .js files. You'd also need to include logic in the client to parse source-maps and process them. This is usually not recommended because you rarely need to show these stacks to end users, they are usually more valuable to you as a developer to understand the reliability of your app. Some companies also deem the name and structure of an application as internal data, and try to not expose that data externally. Because the source-map contains a lot of source information, it may be preferable to not serve it with the app.

* **Server side** (recommended): Usually the workflow looks like this:
  * Client application encounters an error
  * Client application logs the error to a server
  * Server loads .map files from a known location to the server (often it has a storage per release of the app, so it knows where to look depending on the .js file that reported the error)
  * Server then does a deobfuscation step (e.g. running a script similar to what source_map_stack_trace does).

Often developers apply the client-side approach during development, and the server-side approach for production.

### Support deferred loading

It appears that source_map_stack_trace doesn't really support deferred loading that well. It only takes a single .map file as an argument to it's API.

Very often, most failures only mention locations of the main .js file, so often only having that .map file is good enough.

That said, eventually it is valuable to have access all .map files.

It's also worth noting that dart2js includes [additional extensions][1] that are not understood by the standard source-map package. Those extensions include information that helps expand inlined frames and provide more accurate information about a failure. That said, the source-maps are still valid to use without the extension.

We do have an internal tool that we wrote to deobfuscate stacks in [dart2js_tools][2]. This tool handles the extensions and map files for part files on demand, so it may be useful for your needs. This is not a published package though, so it's only available at this time if you are willing to clone the sdk repo it to try it locally, unfortunately. Eventually it would be nice to publish it.

Hope this is helpful!

[1]: https://github.com/dart-lang/sdk/blob/0c5e1e8e4809a90d49f1e6467e80a8a6aef36ef4/pkg/compiler/doc/sourcemap_extensions.md
[2]: https://github.com/dart-lang/sdk/blob/0c5e1e8e4809a90d49f1e6467e80a8a6aef36ef4/pkg/dart2js_tools/bin/deobfuscate.dart#L14

**Comment by fhuonder** [comment]
Hi

I think I can work with your answer.
But there might be cases where it is not satisfying because we use deferred loading and this does, as you said, not work.
The browser can look into the js file to determine which map file to use. I assume that's not possible from the dart code itself.

**Comment by sigmundch** [comment]
> But there might be cases where it is not satisfying because we use deferred loading and this does, as you said, not work.

Thinking more about it I think I was wrong above. Sorry for the misleading information.

I thought initially that `Mapping` had to correspond to a single source-map file, but the API is general enough that it can support multiple files.

I came to realize that the DDC compiler (the development compiler used within webdev and flutter tools) does something similar to what you want to do. The way it's implemented is by providing a `Mapping` that combines the data from multiple source-maps. You can find the sources here: https://github.com/dart-lang/sdk/blob/main/pkg/dev_compiler/web/stack_trace_mapper.dart

The logic it uses to load the .map files is not applicable here, though.

> The browser can look into the js file to determine which map file to use. I assume that's not possible from the dart code itself.

Browsers read a comment at the end of each .js file to find the corresponding .map file. Usually a line like this:

**foo.dart.js**:
```js
...
// sourceMappingURL=foo.dart.js.map
```

The browser resolves the URL in that comment relative to the URL of the .js file. So if `foo.dart.js` is loaded from `http://localhost:8000/a/b/c/foo.dart.js` it will then load the .map file from `http://localhost:8000/a/b/c/foo.dart.js.map`.

From your dart client code it is tricky to read that comment because you don't have access to contents of the script file that easily. That said, our compiler follows a simple convention, every file `x.js` will have a corresponding `x.js.map` file next to it. If your toolchain doesn't rename the files, then you can use this convention to resolve the file you want. You can use `dart:html`'s HttpRequest to fetch the file and parse it at that point as a source-map.
